development:
  adapter: postgresql
  encoding: unicode
  database: profile_db
  username: profile_user
  password: gpo1212

production:
  adapter: postgresql
  encoding: unicode
  database: profile_production
