app:
  domain:    .domain
  secret:    'dd9594b9daa9ac2c0007ca9bd91a48f3429b930ad956730e140723d942e62e27c4e9bbe6eaa84dfc6106fba0f1bafaeb627ed0cda96906844981246dc4dc2a3b'
  from:      'zg_mail@test.ru'
  host:      'localhost:3000'

redis_user_connector:
  url: 'redis://localhost:6379/3'

session_store:
  db:             4
  key_prefix:     'session:'
  host:           'localhost'
  port:           6379

providers:
  # development
  twitter:
    id:           '8kaOVZLPBwE5Z3OEyZAhI3qW0'
    secret:       'EL4bJlV4WzHXBsHKROKfVUcq2DEhRHcZDl3q5LPmAQbyJWYlBp'

    #localhost:3000
  vkontakte:
    id:           5512870
    secret:       '3v1CST9IqjpODXlRC20W'

  facebook:
    id:           '1090856901037576'
    secret:       '1817f2c62283bbbbe158ce72dbd2b27b'

  google_oauth2:
    id:           '771451261680-g8jodo48054qvsabiqnbqag2mg27374i.apps.googleusercontent.com'
    secret:       'r7nJ0JaGqu-p9a1qMtxSweiC'

  yandex:
    id:           'f2e63884596c44899d81086b48ba960a'
    secret:       'f4599fc5175c4a6693994a8562bdf5c0'

  mailru:
    id:           '751785'
    secret:       '8223e99a4e63d8d57240b09aba094f67'

profile:
  url:          'http://localhost:3000'
  sign_in_url:  'http://localhost:3000/users/sign_in'
  sign_up_url:  'http://localhost:3000/users/sign_up'
  sign_out_url: 'http://localhost:3000/users/sign_out'
  edit:         'http://localhost:3000/users/edit'

#redis:
  #url:            'redis://localhost:6379/1'
  #cdn:            'redis://localhost:6379/15'
  #publishing:     'redis://localhost:6379/15'


